### PR TITLE
Add ability to configure issuerDN and cache dir

### LINKED ISSUE #4: X509CertKeyCreator should allow custom issuer DN
Currently we hardcode `issuerDn = new X500Name("C=US,O=Spotify,CN=clienttlstools")`. This should probably be configurable by consumers.

### LINKED ISSUE #5: SshAgentHttpsHandler.CERT_CACHE_DIR should be configurable
Especially if we do #4, then we should make the cache dir configurable and/or require it to be specified by the consumer. This will keep certs from different apps from clobbering each other.

### PR DESCRIPTION
**Pull request by davidxia**
fixes #4
fixes #5

### CODE REVIEW

**Comment by rohansingh** [comment]
Rather than having to specify country, org, etc., separately, I'd lean toward just allowing consumers to specify the whole `issuerDN` as an `X500Name`. That way people can use whatever fields they'd like.

**Comment by rohansingh** [comment]
Also, great that you can configure the cache dir now. Thought about it though and I think we can absolutely stop any potential clobbering of certs with different `issuerDN`, even if they use the same cache dir. We should just add the `issuerDN` to the `identityHash` used to calculate the cache file names.

**Comment by davidxia** [comment]
@rohansingh Thanks for the suggestions. Yea, I thought about letting user specify issuerDN as whatever string they wanted. Makes sense.

**Comment by rohansingh** [comment]
Instead of just a string might actually make sense to accept an actual `X500Name` object. That flexibility could be useful down the road if someone wants to construct the issuer DN using [one of the alternative constructors](http://www.bouncycastle.org/docs/docs1.6/org/bouncycastle/asn1/x500/X500Name.html#X500Name(org.bouncycastle.asn1.x500.RDN[])).

**Comment by davidxia** [comment]
@rohansingh Updated

**Pull request merged**
